id: opecha:P001764
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC21
  title: 'དྲང་ངེས་ལེགས་བཤད་སྙིང་པོའི་བཤད་འཁྲིད་ཟིན་བྲིས་བློ་བཟང་རྒྱལ་བའི་དགོངས་རྒྱན་ལུང་རིགས་གསེར་གྱི་ཐང་མ། '
  volume: ''
  author: ''
