id: I4A44F9CF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T11:01:19+00:00'
last_modified: '2022-06-07T15:04:06.828729+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC21
  title: 'དྲང་ངེས་ལེགས་བཤད་སྙིང་པོའི་བཤད་འཁྲིད་ཟིན་བྲིས་བློ་བཟང་རྒྱལ་བའི་དགོངས་རྒྱན་ལུང་རིགས་གསེར་གྱི་ཐང་མ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    F474:
      image_group_id: I2PD18745
      title: ''
      total_pages: 286
      order: 1
      base_file: F474.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
